services:
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: nest-web_socket
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
